<a href="https://colab.research.google.com/github/rani-sneha/DataScience/blob/main/100-days-of-machine-learning/D26-D50/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
customer='/content/drive/MyDrive/100-days-of-machine-learning/customer.csv'

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(customer)

In [5]:
df.sample(5)

age  gender   review education purchased
34   86    Male  Average    School        No
32   92    Male  Average        UG       Yes
36   34  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
15   75    Male     Poor        UG        No

In [6]:
df = df.iloc[:,2:]

In [7]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,0:2], df.iloc[:, -1], test_size=0.2)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train = oe.transform(X_train)

In [13]:
X_train

array([[1., 2.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:
X_train

array([[1., 2.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.]])

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

LabelEncoder()

In [19]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [21]:
y_train

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1])